export const INIT_APPLICATION = "INIT_APPLICATION";
export const SET_WINDOW_WIDTH = "SET_WINDOW_WIDTH";
export const SET_SORTED_ARTWORKS = "SET_SORTED_ARTWORKS";
export const SET_ARTISTS = "SET_ARTISTS";
export const SET_PATCHNOTES = "SET_PATCHNOTES";
export const SET_SCREENSHOTS = "SET_SCREENSHOTS";
